### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by younesaassila** [keyhr/vscode-42-c-format#1]
`c_formatter_42` now supports Windows but this extension fails to run on Windows because of the following error:

```
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

42-c-format: Please read README and check requirements.
```

Indeed, the default name of the Python 3 interpreter on Windows is just `python`, not `python3`.

**Comment by keyhr** [comment]
Thank you for filing the issue. Since I have no windows machine, I'm not able to test whether the extension works properly. I published the new version ([[update] add windows support](https://github.com/keyhr/vscode-42-c-format/commit/32d905a7d1a215f496f94fa9dc6062cea6afc1be)), would you test it?

**Comment by younesaassila** [comment]
It works perfectly! Thanks!
