### ISSUE TITLE
VS Code can't find c_formatter_42 in python : `/usr/bin/python3: No module named c_formatter_42`

### ISSUE THREAD

**Issue by melobern** [keyhr/vscode-42-c-format#5]
VS-Code tells :
`/usr/bin/python3: No module named c_formatter_42`
I launched the installation again :
```
`pip3 install --user c_formatter_42`
Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: c_formatter_42 in /home/melobern/.local/lib/python3.8/site-packages (0.2.7)
```

If I do `"c_formatter_42 < file.c"` or `"python3 -m c_formatter_42 < file.c"` or even `"c_formatter_42 file.c"` in my terminal, it works.
In Vim and Neovim, `<F2> ` works as well.
The only place where I have this problem is in VS Code and I couldn't find how to fix this.

**Comment by keyhr** [comment]
I assume this happens because the child process uses a different python than the one you use in your terminal. Can you show me where the `python3` exists in the terminal?

```
$ which python3
```

**Comment by melobern** [comment]
`which python3` gives `/usr/bin/python3` too, the same VS Code tells it can't find c_formatter_42 in it.

**Comment by melobern** [comment]
When I ask the terminal to echo `$PYTHONPATH`, it doesn't give the same address as `which python`. 
```
➜  ~ echo $PYTHONPATH 
:/home/melobern/.local/lib/python3.8/site-packages:/home/mbernard/.local/lib/python3.8/site-packages
➜  ~ which python3
/usr/bin/python3
```

I tried to change the path in VS Code but it didn't recognize the variable when I put them in settings.json :
`"python.pythonPath": "/home/melobern/.local/lib/python3.8/site-packages"`
or
`"python.defaultInterpreterPath": "/home/melobern/.local/lib/python3.8/site-packages"`

**Comment by melobern** [comment]
The school updated computers, it works now. Hope no one else will encounter this problem again at the school.
I close this issue.
If someone has this problem again, it works and I don't have anything more than this in my settings.json :
```
"terminal.integrated.defaultProfile.linux": "zsh",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "/usr/bin/flatpak-spawn",
            "args": [
                "--host",
                "--env=TERM=xterm-256color",
                "zsh",
            ]
        }
    },
    "workbench.colorTheme": "Default Dark Modern",
    "[c]": {
        "editor.defaultFormatter": "keyhr.42-c-format"
    },
    "editor.wordWrap": "on",
    "editor.minimap.enabled": false,
    "editor.formatOnSave": true,
    "files.autoSave": "onFocusChange",
    "cmake.configureOnOpen": true,
    "cmake.showOptionsMovedNotification": false,
    "window.zoomLevel": 3,
    "editor.fontSize": 12,
    "git.openRepositoryInParentFolders": "always",
    "42header.username": "my_login",
    "42header.email": "my_login@student.42.fr",
```
